# Generated by Django 4.2.1 on 2023-07-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
