# Generated by Django 4.2.1 on 2023-07-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_recursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cantidad_libros',
            new_name='cantidad_libro',
        ),
        migrations.RenameModel(
            old_name='cantidad_tesis',
            new_name='cantidad_trabajo',
        ),
    ]
