# Generated by Django 4.2.1 on 2023-07-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenina'), ('O', 'Prefiero no definirlo')], max_length=1),
        ),
    ]
