# Generated by Django 4.2.1 on 2023-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibile_a_prestamos',
            old_name='id_libro',
            new_name='id_recurso',
        ),
        migrations.AddField(
            model_name='disponibile_a_prestamos',
            name='tipo_recurso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
