# Generated by Django 4.2.1 on 2023-07-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0002_rename_id_libro_disponibile_a_prestamos_id_recurso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponible_a_Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recurso', models.IntegerField()),
                ('n_disponibles', models.IntegerField()),
                ('tipo_recurso', models.IntegerField()),
                ('tipo_prestamo', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disponible_a_Prestamo',
                'verbose_name_plural': 'Disponibles_a_Prestamos',
            },
        ),
        migrations.DeleteModel(
            name='Disponibile_a_Prestamos',
        ),
    ]
