# Generated by Django 4.2.1 on 2023-07-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0004_alter_prestamo_estado_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso_Disponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recurso', models.IntegerField()),
                ('tipo_recurso', models.IntegerField()),
                ('n_disponibles', models.IntegerField()),
                ('tipo_prestamo', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurso_Disponible',
                'verbose_name_plural': 'Recursos_Disponibles',
            },
        ),
        migrations.DeleteModel(
            name='Disponible_a_Prestamo',
        ),
    ]
