# Generated by Django 4.2.1 on 2023-07-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0005_recurso_disponible_delete_disponible_a_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso_disponible',
            name='n_disponibles',
            field=models.PositiveBigIntegerField(),
        ),
    ]
