# Generated by Django 4.2.1 on 2023-07-27 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('edicion', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('isbn', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=50)),
                ('palabras_clave', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.CreateModel(
            name='cantidad_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_recursos.trabajo')),
            ],
            options={
                'verbose_name': 'cantidad trabajo',
            },
        ),
        migrations.CreateModel(
            name='cantidad_libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_recursos.libro')),
            ],
            options={
                'verbose_name': 'cantidad libro',
            },
        ),
    ]
