# Generated by Django 4.2.1 on 2023-07-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_recursos', '0004_alter_trabajo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
